name: render-quarto

on:
  push:
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::jsonlite
            any::htmltools
            any::knitr
            any::rmarkdown
            any::reticulate
      - name: "Quarto Render"
        shell: bash
        run: |
          quarto render
      - name: "Configure Pages"
        uses: actions/configure-pages@v5
      - name: "Upload Pages Artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_output"
      - name: "Deploy Pages"
        id: deployment
        uses: actions/deploy-pages@v4
